#!/usr/bin/env python3

# Transfer locally saved QC'd metadata to the raw Google bucket
# Usage:
#   Single dataset:
#     python3 transfer_qc_metadata_to_raw_bucket -d team-jakobsson-pmdbs-bulk-rnaseq -v v4.0.1 -p
#
# Batch processing (datasets.csv field 1 is is dataset id, field 2 is release version, no header):
#     while IFS=, read -r team dataset; do
#         python3 transfer_qc_metadata_to_raw_bucket -d "$dataset_id" -p
#     done < datasets.csv
#
# Defaults to dry run unless -p flag is added!
# 
# NOTE on assumptions made:
# 1.   You have cloned asap-crn-cloud-dataset-metadata and its root is at the
# ---- same level as wf-common
# 2.   The metadata/ directory of the target dataset exists locally and contains
# ---- the finalized QC'd metadata structure (original/, cde/, and 
# ---- release/{release_version} dirs)
# 3.   The file_metadata/ directory exists locally and is populated with the files
# ---- artifacts.csv, raw_files.csv, and curated_files.csv

import argparse
import logging
from pathlib import Path
from common import gsync, strip_team_prefix, gcopy
from bucket_validation_utils import (
    FILE_METADATA_FILES,
    check_bucket_exists,
    check_original_metadata_exists_locally,
    validate_local_metadata_structure
)


logging.basicConfig(
	level=logging.INFO,
	format="%(asctime)s - %(levelname)s - %(message)s"
)

repo_root = Path(__file__).resolve().parents[1]
metadata_root = repo_root.parent / "asap-crn-cloud-dataset-metadata"


def main(args):

    dry_run = not args.promote
    
    dataset_id = args.dataset_id
    dataset_name = strip_team_prefix(dataset_id)
    bucket_name = f"gs://asap-raw-{dataset_id}"
    release_version = args.release_version
    
    dataset_dir = metadata_root / "datasets" / dataset_name
    metadata_dir = dataset_dir / "metadata"
    file_metadata_dir = dataset_dir / "file_metadata"
    doi_dir = dataset_dir / "DOI"
    
    metadata_bucket = f"{bucket_name}/metadata"
    file_metadata_bucket = f"{bucket_name}/file_metadata"
    doi_bucket = f"{bucket_name}/DOI"
    
    check_bucket_exists(bucket_name)
    
    # Validate local metadata structure before transfer
    is_cohort = dataset_name.startswith("cohort")
    validate_local_metadata_structure(metadata_dir, is_cohort=is_cohort, release_version=release_version)

    # Transfers entire metadata/ directory
    if metadata_dir.exists():
        logging.info(f"Transferring local metadata directory to [{metadata_bucket}]")
        
        # Early exit if original metadata is missing: implies incomplete QC
        if not check_original_metadata_exists_locally(metadata_dir):
            raise ValueError(f"original/ directory is missing in local metadata dir: {metadata_dir}")
        
        gsync(
            source_path=str(metadata_dir),
            destination_path=metadata_bucket,
            dry_run=dry_run
        )
    else:
        raise ValueError(f"Local metadata directory not found: {metadata_dir}")

    # Transfer file_metadata/ files
    if file_metadata_dir.exists():
        logging.info(f"Transferring selected local file_metadata/ files to [{file_metadata_bucket}]")
        for file_name in FILE_METADATA_FILES:
            file_path = file_metadata_dir / file_name
            if file_path.exists():
                if dry_run:
                    logging.info(f"Would copy {file_path} to {file_metadata_bucket}/{file_name}")
                else:
                    logging.info(f"Transferring file: {file_name}")
                    gcopy(
                        source_path=str(file_path), 
                        destination_path=f"{file_metadata_bucket}/{file_name}",
                        recursive=False
                    )
            else:
                logging.warning(f"File not found, skipping: {file_name}")
    else:
        raise ValueError(f"Local file metadata directory not found: {file_metadata_dir}")
    
    # Transfers DOI/
    if doi_dir.exists():
        logging.info(f"Transferring local DOI/ directory to [{doi_bucket}]")
        
        gsync(
            source_path=str(doi_dir), 
            destination_path=doi_bucket, 
            dry_run=dry_run
        )
    else:
        logging.warning(f"Local DOI directory not found, skipping transfer: {doi_dir}")
 

if __name__ == "__main__":
    
    parser = argparse.ArgumentParser(
		description="Sync local metadata directories to raw bucket"
	)
    
    parser.add_argument(
        "-d",
        "--dataset-id",
        type=str,
        required=True,
        help="Dataset ID in bucket name (e.g., team-jakobsson-pmdbs-sn-rnaseq)."
    )
    parser.add_argument(
        "-v",
        "--release_version",
        required=True,
        help="The release version of the dataset (e.g., v4.0.1)."
    )
    parser.add_argument(
        "-p",
		"--promote",
		action="store_true",
		required=False,
		help="Promote data (default is dry run)."
	)

    args = parser.parse_args()

    if not (args.dataset_id.startswith("team") or args.dataset_id.startswith("cohort")):
        raise SystemExit(
            f"--dataset-id must start with 'team' or 'cohort', got: '{args.dataset_id}'"
        )

    main(args)
